name: NoSpectatorColor
version: @version@
main: com.github.sigureruri.nospectatorcolor.NoSpectatorColor
api-version: 1.13
authors: [SigureRuri]
depend: [ProtocolLib]
permissions:
  nospectatorcolor.invalid:
    default: false
  nospectatorcolor.check:
    default: false
